### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by nolife08021** [ShaMan123/react-native-math-view#16]
Failed to install with "npm install --save react-native-math-view"

npx: installed 1 in 2.895s
error TS5023: Unknown compiler option 'downlevelIteration'.
error TS5023: Unknown compiler option 'lib'.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mathjax-full@3.0.0 compile: `npx tsc`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mathjax-full@3.0.0 compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/admin/.npm/_logs/2019-11-18T02_56_23_447Z-debug.log
fs.js:114
    throw err;
    ^

Error: ENOENT: no such file or directory, copyfile '/Users/admin/myMathProject/node_modules/mathjax-full/ts/input/tex/mhchem/mhchem_parser.js' -> '/Users/admin/myMathProject/node_modules/mathjax-full/js/input/tex/mhchem/mhchem_parser.js'
    at Object.copyFileSync (fs.js:1728:3)
    at Object.<anonymous> (/Users/admin/myMathProject/node_modules/react-native-math-view/scripts/compileMathjax.js:22:4)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

 Error: react-native-math-view@3.3.4 postinstall: `node ./scripts/compileMathjax && tsc`
 Exit status 1
 at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm- 
 lifecycle/index.js:301:16)
 at EventEmitter.emit (events.js:198:13)
 at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm- 
 lifecycle/lib/spawn.js:55:14)
 at ChildProcess.emit (events.js:198:13)
 at maybeClose (internal/child_process.js:982:16)
 at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
 pkgid react-native-math-view@3.3.4

**Comment by joaortizro** [comment]
Error: ENOENT: no such file or directory, copyfile '/home/kib/Projects/KIB/kibApp/node_modules/mathjax-full/ts/input/tex/mhchem/mhchem_parser.js' -> '/home/kib/Projects/KIB/kibApp/node_modules/mathjax-full/js/input/tex/mhchem/mhchem_parser.js'
    at Object.copyFileSync (fs.js:1731:3)
    at Object.<anonymous> (/home/kib/Projects/KIB/kibApp/node_modules/react-native-math-view/scripts/compileMathjax.js:22:4)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11 {
  errno: -2,
  syscall: 'copyfile',
  code: 'ENOENT',
  path: '/home/kib/Projects/KIB/kibApp/node_modules/mathjax-full/ts/input/tex/mhchem/mhchem_parser.js',
  dest: '/home/kib/Projects/KIB/kibApp/node_modules/mathjax-full/js/input/tex/mhchem/mhchem_parser.js'
}

**Comment by nolife08021** [comment]
@ShaMan123  kindly advice, I really need this, rather than using webview.

**Comment by joaortizro** [comment]
@ShaMan123 i've tried Math example from the repo but still same errors, @nolife08021 have you tried the mathExample, may be im missing something out...

**Comment by nolife08021** [comment]
@joaortizro I tried just now and this error comes out.

error: bundling failed: Error: Unable to resolve module `mathjax-full/js/input/tex/AllPackages` from `/Users/admin/react-native-math-view/src/mathjax/Config.ts`: Module `mathjax-full/js/input/tex/AllPackages` does not exist in the Haste module map or in these directories:
  /Users/admin/react-native-math-view/node_modules/mathjax-full/js/input/tex

**Comment by nolife08021** [comment]
@joaortizro I able to run the mathExample now after install mathjax-full and transformation-matrix in react-native-math-view as error log mention. But I still wondering how to use it in my apps.

**Comment by ShaMan123** [comment]
Will look into it.
BTW iOS isn't working yet so file an issue if the fallback component isn't working

**Comment by ShaMan123** [comment]
I tried to reproduce the issue. It is something I ran into before but couldn't reproduce anymore.
To test the issue I installed the package on a new react-native app both with `yarn` and `npm` with no trouble.
Just in case I went through the config files for the example app and made them more safe, upgraded `react-native` and bumped the version.
I suggest you remove all `node_modules` + `lockfile`, download again, **rebuild** example app and see how it goes.
Make sure to follow these [instructions](https://github.com/ShaMan123/react-native-math-view#running-example-app)
What version of `react-native` are you using?
If you are using with `iOS` be sure to add `react-native-svg` (this is a fallback until I finish linking the native code)
Report back so I can help.

**Comment by ShaMan123** [comment]
@nolife08021 @joaortizro I've added additional info in the ReadME. Suggest you guys give it a look

**Comment by ShaMan123** [comment]
@nolife08021 after installing if the bug persists try running:
```bash
cd node_modules/react-native-math-view && npm run postinstall

```
and report back.
Thanks

**Comment by ShaMan123** [comment]
Might have found the problem. bumped -> 3.4.1

**Comment by joaortizro** [comment]
@nolife08021 @ShaMan123 , i've managed to at least run the mathExample but now it seems there are some errors with the hooks

- node version : 12.4.0
- react-native-cli: 2.0.1
- react-native: 0.61.4

![1](https://user-images.githubusercontent.com/20843665/69074683-dd284080-09fd-11ea-8f40-22c881e8f631.png)
![2](https://user-images.githubusercontent.com/20843665/69074693-e0bbc780-09fd-11ea-88a1-3aee93527b12.png)

**Comment by nolife08021** [comment]
@ShaMan123    I'm facing this error after I removed all node_modules + lockfile and download it again. 

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-native-math-view@3.4.1 postinstall: `node ./scripts/compileMathjax`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-native-math-view@3.4.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/admin/.npm/_logs/2019-11-19T02_48_35_163Z-debug.log
```

 "react-native": "0.59.5"

**Comment by ShaMan123** [comment]
[Make sure it's not a problem with your environment](https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react).
I think that downgrading is not a good idea.
This error is not vital and can be disregarded.
I've edited the [installation guide](../#errors-during-installation).

**Comment by ShaMan123** [comment]
I think that downgrading is not a good idea.
This error is not vital and can be disregarded.
I've edited the [installation guide](../#errors-during-installation).

**Comment by ShaMan123** [comment]
and perhaps try the following:
1. Clean cache for `npm` and `yarn` (sometimes for yarn you need to do it manually by navigating to the cache dir and deleting it)
1. Remove `react-native` global package (`npm uninstall -g react-native`)

**Comment by joaortizro** [comment]
i tried 1,2,4, and 5 by running `./gradlew clean` inside the android folder, i dont know if this is what you mean by **clean and rebuild native code** to be honest, and still got the error without the `compiled mathjax successfully`

i will try option 3 asap , since i've other project on it and kinda scared to mess things up

**Comment by ShaMan123** [comment]
Try it on a new project

בתאריך יום ה׳, 21 בנוב׳ 2019, 01:03, מאת joaortizro ‏<
notifications@github.com>:

**Comment by joaortizro** [comment]
@ShaMan123 it was a completely new project

May i ask your react, react-native, react-dom version?

**Comment by ShaMan123** [comment]
```diff
 "dependencies": {
+    "react": "16.9.0",
+    "react-native": "0.61.4",
    "react-native-gesture-handler": "^1.5.0",
    "react-native-reanimated": "^1.4.0",
+    "react-native-svg": "^9.13.3"
  },
```

no need for react-dom. This repo is native only.

![example](https://user-images.githubusercontent.com/34343793/69400303-d4838300-0cf9-11ea-843e-a89d1244e2a4.jpeg)

**Comment by joaortizro** [comment]
i've upgraded to react 16.9.0 and native to 0.61.4

![image](https://user-images.githubusercontent.com/20843665/69460546-77f88600-0d42-11ea-8096-070a33c93653.png)

but `yarn add react-native-math-view` doesn't show `compiled-mathjax-successfuly`

i will add the full log generated by npm 
[2019-11-22T21_15_30_640Z-debug.log](https://github.com/ShaMan123/react-native-math-view/files/3881490/2019-11-22T21_15_30_640Z-debug.log)

**Comment by ShaMan123** [comment]
Do you have `npx` installed globally?
If you ignore this error what happens?
Did you read [this](https://github.com/ShaMan123/react-native-math-view#errors-during-installation)?

**Comment by joaortizro** [comment]
ok, so with yarn it does install the library but when i called it says 

Error: Unable to resolve module `mathjax-full/js/input/tex/AllPackages` from `node_modules/react-native-math-view/src/mathjax/Config.ts`: mathjax-full/js/input/tex/AllPackages could not be found within the project.
yes i have `npx` globally,

**Comment by ShaMan123** [comment]
[update typescript version](https://stackoverflow.com/questions/43815501/typescript-error-ts5023-unknown-compiler-option-strict/43815625)
beyond this I am unable to help

**Comment by joaortizro** [comment]
Wow updating typescript does the job, sorry for this lack of debugging i mainly use JS

Thank you ! i will try this on my actual app  

![finally](https://user-images.githubusercontent.com/20843665/69501920-9e9bf580-0ed7-11ea-96ab-bd30942cdd93.png)

**Comment by ShaMan123** [comment]
I just managed to debug on ios and found the problem for the duplicate hook call.
Should be resolved.
bumping version.

**Comment by rolaay** [comment]
> Apparently i did have a problem with **mathjax-full** , i've tried to add it but still same error
> 
> `Error: ENOENT: no such file or directory, copyfile '/home/kib/Projects/KIB/kibApp/node_modules/mathjax-full/ts/input/tex/mhchem/mhchem_parser.js' -> '/home/kib/Projects/KIB/kibApp/node_modules/mathjax-full/js/input/tex/mhchem/mhchem_parser.js' at Object.copyFileSync (fs.js:1731:3) at Object.<anonymous> (/home/kib/Projects/KIB/kibApp/node_modules/react-native-math-view/scripts/compileMathjax.js:22:4) at Module._compile (internal/modules/cjs/loader.js:774:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10) at Module.load (internal/modules/cjs/loader.js:641:32) at Function.Module._load (internal/modules/cjs/loader.js:556:12) at Function.Module.runMain (internal/modules/cjs/loader.js:837:10) at internal/main/run_main_module.js:17:11 { errno: -2, syscall: 'copyfile', code: 'ENOENT', path: '/home/kib/Projects/KIB/kibApp/node_modules/mathjax-full/ts/input/tex/mhchem/mhchem_parser.js', dest: '/home/kib/Projects/KIB/kibApp/node_modules/mathjax-full/js/input/tex/mhchem/mhchem_parser.js' }`

Please have you been able to resolved this

**Comment by rolaay** [comment]
> [update typescript version](https://stackoverflow.com/questions/43815501/typescript-error-ts5023-unknown-compiler-option-strict/43815625)
> beyond this I am unable to help

This worked for me. Thank you.
