### ISSUE TITLE
IOS Linking Error

### ISSUE THREAD

**Issue by Kings-dev-02** [ShaMan123/react-native-math-view#17]
Hi ShaMan,

In Andriod running perfectly 

In Ios Getting below error:

error Could not find the following native modules: react-native-math-view, RNSVG. Did you forget to run "pod install"?

On running Pod install 
cd ios && pod install

Getting Below Error:

Detected React Native module pods for RNSVG and react-native-math-view
Analyzing dependencies
[!] The `react-native-math-view` pod failed to validate due to 2 errors:
    - ERROR | license: Sample license type.
    - ERROR | description: The description is empty.

Any Help!!!!!!!

Thanks,
Kings

**Comment by ShaMan123** [comment]
hmmm... I can't say. No mac present.
Does the example app work? I checked that last publish.
Did you follow `react-native-svg` installation guide?

If `react-native-math-view` pod is troublesome for this version it can be removed safely as it is incomplete. `react-native-svg` is used as fallback. Next version this will change.

PR is welcome!

**Comment by ShaMan123** [comment]
I see the problem.
Try deleting the file `ios/react-native-math-view.podspec`. I thought it had been deleted.

**Comment by Kings-dev-02** [comment]
G8 it works, Thanks ShaMan.

one more thing how to show as inline, formula blocks the entire line.

**Comment by ShaMan123** [comment]
check out `MathExample` for code, navigate to `Fallback`.
I bumped the version so you can re-install -> `3.4.3`

**Comment by ShaMan123** [comment]
BTW next major version ios will depart of `react-native-svg` in favor of `iosMath` which is fantastic and renders at 1/10 the time
