### ISSUE TITLE
TypeError: null is not an object (evaluating '_ref.Constants')

### ISSUE THREAD

**Issue by rajeevrjha** [ShaMan123/react-native-math-view#20]
![Screenshot_20191222-021516](https://user-images.githubusercontent.com/10881340/71313643-803b0280-2461-11ea-9446-3ab4489b06eb.png)
I am trying to use MathView within an Expo Project (Expo SDK 36.0). The output is on Android.

I suspect this is because RNMathView java package does not get linked but I am not sure.

Please help!

**Comment by ShaMan123** [comment]
duplicate #19

**Comment by pixelmath** [comment]
Thanks...this was helpful
