### ISSUE TITLE
How do you wrap the content ?

### ISSUE THREAD

**Issue by sumesh1993** [ShaMan123/react-native-math-view#21]
I have big question, it is rendering in one line. How do i wrap it such that it comes on the next line 

<img width="366" alt="Screenshot 2019-12-24 at 9 11 26 PM" src="https://user-images.githubusercontent.com/4946706/71418746-28371280-2692-11ea-9c78-40255df82f89.png">

**Comment by ShaMan123** [comment]
Well, that's a question. A very complicated one.
The simplest approach would be to render this math into 3 MathViews, then apply styling on the parent container view.

**Comment by sumesh1993** [comment]
i figured out a way, but `/begin{flushleft}` and `\end{flushright}` doesnt seem to be working

**Comment by ShaMan123** [comment]
Try looking into mathjax docs

**Comment by sumesh1993** [comment]
Does your library use mathjax under the hood for iOS and Android ? Because on web the latex is rendering perfectly using mathjax, but on iOS its not working as expected.
This is the latex `When $a \ne 0$, there are two solutions to \(ax^2 + bx + c = 0\) and they are
$$x = {-b \pm \sqrt{b^2-4ac} \over 2a}.$$`

**Comment by ShaMan123** [comment]
On the web it surely wraps content with no issues. `MathJax` is designed mainly for web and not long ago they started supporting `nodejs` rendering. This library is an adaption of the node version, therefore lacking a true renderer and defaulting to svg.
This is why you can't wrap content, it's svg. 
iOS might manage this once rendering will be done by a native library (can't say yet, haven't had the time) and there might be a very complex way to do this with svg (or component mirroring from web to RN) but it isn't on the roadmap.
PRs are welcome.

**Comment by ShaMan123** [comment]
BTW the android version has a `scaleToFit` prop that might help in some manner.

**Comment by ShaMan123** [comment]
A final thought:
If it's crucial you could use a `WebView` and some internals of the mathjax adaptor to render html string.
This should work

**Comment by ShaMan123** [comment]
#22
