### ISSUE TITLE
Unable to resolve module

### ISSUE THREAD

**Issue by ggunti** [ShaMan123/react-native-math-view#24]
I get this error on iOS:
<img width="315" alt="Captură de ecran din 2020-04-03 la 00 21 23" src="https://user-images.githubusercontent.com/26307699/78301021-260e0b00-7541-11ea-8744-1ae53929a3ea.png">

**Comment by ShaMan123** [comment]
Try updating `typescript` dependency.

**Comment by ggunti** [comment]
Thanks! I just reinstalled the `react-native-math-view` library and now it works.

**Comment by SirTitch** [comment]
Hi @ShaMan123 we have ran into this as well but updating typescript to v4.2.4 the most recent version doesn't seem to fix it, i get this error when running npm install & npm install react-native-math-view:
![Screenshot from 2021-05-12 18-51-47](https://user-images.githubusercontent.com/35763984/118021834-9053ca80-b353-11eb-8b3d-013bd06ac8cd.png)
![Screenshot from 2021-05-12 18-52-10](https://user-images.githubusercontent.com/35763984/118021837-90ec6100-b353-11eb-8b1e-70801782ad7c.png)

**Comment by ShaMan123** [comment]
@SirTitch #16

**Comment by ShaMan123** [comment]
@SirTitch this is a persistant bug. 
1. Make sure `mathjax-full` is installed.
2. run the failed script directly from `react-native-math-view` directory: [npm run postinstall](https://github.com/ShaMan123/react-native-math-view/blob/master/package.json#L13)
