### ISSUE TITLE
Inline mode vs not inline mode

### ISSUE THREAD

**Issue by ggunti** [ShaMan123/react-native-math-view#27]
Hello!
What I observed is that 'MathView' always render math in inline mode. Is it possible to render somehow the math also in non-inline mode?

Example (inside MathJax):
<img width="1230" alt="Captură de ecran din 2020-04-18 la 12 10 48" src="https://user-images.githubusercontent.com/26307699/79633460-6343e100-816e-11ea-93db-10c5492b509d.png">

As you can see, in inline mode the `n->infinity` is passed to the right of `lim`, but I would like to keep it below `lim`, like in non-inline mode. Is it possible?

**Comment by ShaMan123** [comment]
This should do the job
```ts

<MathView config={{inline:false}} />

```

**Comment by ggunti** [comment]
It works, thank you!

**Comment by ShaMan123** [comment]
What do to pass as `math` props? Does it include `$$`?

**Comment by ggunti** [comment]
No, it does not include '$$', only the math expression string, without '$$'.

**Comment by ShaMan123** [comment]
Thanks
