### ISSUE TITLE
Content not rendering

### ISSUE THREAD

**Issue by AIRLegend** [ShaMan123/react-native-math-view#28]
Hello,

My app does not render the LaTeX code, although it shows the component:

![Captura de pantalla 2020-04-20 a las 15 53 44](https://user-images.githubusercontent.com/9653892/79759824-75b14c80-831f-11ea-834c-14dd6eb96936.png)

This is the corresponding code:

```js
import React from 'react';
import { StyleSheet, Text, View, ScrollView} from 'react-native';
import MathView from 'react-native-math-view';
import MathViewFallback from 'react-native-math-view/src/fallback';

const math = 'x=\\frac{-b\\pm\\sqrt{b^2-4ac}}{2a}';

export default function RankingScreen({navigation}) {
  return (
    <View style={styles.container}>
        <MathView math={math} config={{ ex: 50 }} style={{backgroundColor: 'red'}}/>
        <Text>Hello world</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: 'column',
    backgroundColor: '#555',
    justifyContent: 'center',
    alignContent: "center",
  },
});
```

I already tried setting different versions of "react-native-svg". Currently I'm using "react-native-svg": "^12.0.1" since all the others give me errors.

(Note: I'm using React Native 0.61.4).

Any ideas?

Thanks in advance.

**Comment by ShaMan123** [comment]
try removing `config={{ ex: 50 }}`

**Comment by AIRLegend** [comment]
I've already tried. The effect is the same but the component becomes smaller...

**Comment by ShaMan123** [comment]
how about this?
```diff
const styles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: 'column',
    backgroundColor: '#555',
-    justifyContent: 'center',
-    alignContent: "center",
  },
});
```

**Comment by AIRLegend** [comment]
Removing the styles doesn't work either. Could it be related to the `react-native-svg` dependency?

**Comment by ShaMan123** [comment]
The question is how if so.
Look here [Example/SvgXml](https://github.com/ShaMan123/react-native-math-view/blob/master/MathExample/src/SvgXml.tsx)
I suggest you run the example and see if that works

**Comment by AIRLegend** [comment]
I managed to get the example app running correctly.  However it does not work on my app. I installed it through `npm install --save react-native-math-view` and `npm install react-native-svg` (the versions above). This is right, isn't it?

**Comment by ShaMan123** [comment]
The example app isn't included in the npm release. Pull from github.

**Comment by AIRLegend** [comment]
Yeah, I mean, I did it and ran it and it works. The problem is related to my app. The process I followed for installing `react-native-math-view` was the above. Is it ok?

**Comment by AIRLegend** [comment]
I've managed to fix it. Simply deleted node_modules and reset metro's cache (`rm -fr $TMPDIR/metro*`). Now it works as expected. Thank you!
