### ISSUE TITLE
How to change the dilimiter?

### ISSUE THREAD

**Issue by Sahejmaharjan1** [ShaMan123/react-native-math-view#31]
Bug reports are filed via the **Bug report** template.

**Comment by ShaMan123** [comment]
I can't address this without proper explanation

**Comment by Sahejmaharjan1** [comment]
How do i get this?
![image](https://user-images.githubusercontent.com/52502614/83938910-55b6e900-a7f8-11ea-9f52-c64c74682c50.png)
It gives
![image](https://user-images.githubusercontent.com/52502614/83938928-74b57b00-a7f8-11ea-86a9-fa2bd60f4af8.png)
