### ISSUE TITLE
How to know if rendering is failed?

### ISSUE THREAD

**Issue by uragirii** [ShaMan123/react-native-math-view#34]
Sometimes, when LaTeX is not correct I'm getting a black bar in place. I want to show an error message like `Error loading LaTeX` or something. Is there a prop for that?

Thank you for the awesome library btw.

**Comment by ShaMan123** [comment]
Thanks for opening this issue.
I've managed to work out a solution.
You should upgrade the package to the latest version `3.5.0`
You can pass a prop to the `MathView` called `renderError`.
Let me know if it works as expected.
