### ISSUE TITLE
Inline in MathJax and react-native-math-view

### ISSUE THREAD

**Issue by zinnen** [ShaMan123/react-native-math-view#37]
Inline or standalone math formulas are displayed different in the library compared to MathJax and LaTeX: 

The attached file contains an example. 
 
You can test the correct LaTeX behavior on: 
"https://www.mathjax.org/#demo: "
using 
“$\sum_{n=0}^\infty$ $$\sum_{n=0}^\infty$$”
 
I would be surprised if you could not set this parameter when generating the SVG? Please excuse me for drilling so much. If I am completely wrong, please let me know. 
<img width="689" alt="Bildschirmfoto 2021-01-08 um 14 59 03" src="https://user-images.githubusercontent.com/9108609/104023536-1acbc800-51c2-11eb-825c-b0a0c102800d.png">

**Comment by ShaMan123** [comment]
try the following:
```tsx
<MathView 
 config={{inline:false}}
/>
```

**Comment by ShaMan123** [comment]
acc077e

**Comment by zinnen** [comment]
Thanks a lot. Perfect!!! Works.

Von: ShaMan123 <notifications@github.com>
Antworten an: ShaMan123/react-native-math-view <reply@reply.github.com>
Datum: Freitag, 8. Januar 2021 um 15:24
An: ShaMan123/react-native-math-view <react-native-math-view@noreply.github.com>
Cc: Andreas Zinnen <Andreas.Zinnen@hs-rm.de>, Author <author@noreply.github.com>
Betreff: Re: [ShaMan123/react-native-math-view] Inline in MathJax and react-native-math-view (#37)


try the following:

<MathView

 config={{inline:false}}

/>

**Comment by ShaMan123** [comment]
V3.7.1
