### ISSUE TITLE
Unknown environment in the examples

### ISSUE THREAD

**Issue by zinnen** [ShaMan123/react-native-math-view#39]
When starting the sample app, the following error of an unknown environment occurs when loading "MathSectionList.tsx": 

<img width="329" alt="Bildschirmfoto 2021-01-13 um 09 30 01" src="https://user-images.githubusercontent.com/9108609/104426309-10267f80-5582-11eb-967a-37d34a3fac0a.png">

**Comment by ShaMan123** [comment]
This is raised because of a chem latex that isn't supported or is wrong

בתאריך יום ד׳, 13 בינו׳ 2021, 10:32, מאת zinnen ‏<notifications@github.com>:
