### ISSUE TITLE
after run yarn add react-native-math-view his dependencies are not installed in his node_modules

### ISSUE THREAD

**Issue by wiliamtaesunglee** [ShaMan123/react-native-math-view#40]
![Captura de Tela 2021-01-13 às 16 58 48](https://user-images.githubusercontent.com/41973973/104504023-9d88c480-55c0-11eb-848b-37500c19f4e3.png)

**Comment by wiliamtaesunglee** [comment]
to resolve that a need run:

cd node_mudules/react-native-math-view && yarn

**Comment by ShaMan123** [comment]
weird.
It should have run the compiling script

**Comment by ShaMan123** [comment]
This should be resolved now.
Please reopen if this presists
