### ISSUE TITLE
Unrecognized font Family 'serif'

### ISSUE THREAD

**Issue by soufian97** [ShaMan123/react-native-math-view#42]
**Describe the bug**
Once I want to get the mathematical formula of the text below in "To Reproduce", the application throws an error with this message: "Unrecognized font Family 'serif'"

**To Reproduce**
 <MathText
                value={"$\\text{Côté}^2$"}
                direction="ltr"
                CellRendererComponent={<TouchableOpacity />}
              />
**Expected behavior**
get correctly the mathematical formula without error

**Comment by ShaMan123** [comment]
I haven't used mathjax with special characters yet.
So I'm guessing the error points that mathjax needs a font that isn't available to render the letters.
Look here:
https://docs.mathjax.org/en/latest/output/fonts.html?highlight=font#mathjax-font-support
I would try to see if there's a way to load the font or to workaround

**Comment by ShaMan123** [comment]
Possible workaround would be:
```diff
- value="$\text{Côté}^2$"
+ value="Côté$^2$"
```

**Comment by soufian97** [comment]
thank you, how can I add please this font because it still some texts that need to install the font

**Comment by ShaMan123** [comment]
I don't know

בתאריך יום ד׳, 27 בינו׳ 2021, 02:55, מאת soufian97 ‏<
notifications@github.com>:

**Comment by ShaMan123** [comment]
From the docs:
> MathJax version 3 currently supports only one font, the MathJax TeX font


Closing: a mathjax issue
