### ISSUE TITLE
How to draw \begin{cases} ?

### ISSUE THREAD

**Issue by jcde** [ShaMan123/react-native-math-view#46]
When trying to draw cases with latex like 
$\begin{cases}-5x+45>0\\\\\\3x+4>0\end{cases}$

I see the message:
LaTex parsing Error, Object {
  "id": "EnvMissingEnd",
  "math": "\\begin{cases}",
  "message": "Missing \\end{cases}",
}
 
https://www.mathjax.org/#demo works normally and README.md links to "MathJax Supported LaTeX Commands" that includes \begin{cases}.

Do you have plans to support \begin{cases} ?

**Comment by ShaMan123** [comment]
You have a typo
![image](https://user-images.githubusercontent.com/34343793/120691064-abc37880-c4ae-11eb-9203-06cff3db42f4.png)

![image](https://user-images.githubusercontent.com/34343793/120691035-a23a1080-c4ae-11eb-96dc-02263ade6d31.png)

This repo uses mathjax under the box, so whatever works there should work here

**Comment by ShaMan123** [comment]
This repo uses mathjax under the box, so whatever works there should work here
