### ISSUE TITLE
Curly braces are broken to 3 pieces

### ISSUE THREAD

**Issue by Porizm** [ShaMan123/react-native-math-view#59]
Hello,

I am using Bmatrix and the curly braces are being broken to 3 pieces when adding 4 lines

![Screen Shot 2021-11-08 at 10 05 52 PM](https://user-images.githubusercontent.com/2933548/140810782-df824aac-413a-48b3-a99d-426265a1b2ff.png)

Tested on iOS 10

Is there a way to fix this?

Thank you in advance

**Comment by ShaMan123** [comment]
Please file a **FULL** [bug report](https://github.com/ShaMan123/react-native-math-view/issues/new?assignees=&labels=&template=bug_report.md&title=Curly%20braces%20are%20broken%20to%203%20pieces)
