### ISSUE TITLE
Everything working and then suddenly got RNMathView" was not found in the UIManager.

### ISSUE THREAD

**Issue by xMxster** [ShaMan123/react-native-math-view#63]
Everything worked fine, and it suddenly stopped worked.
I deleted all files related to my project, removed and reinstalled math view, and I kept getting this error 

This is the file I'm using
`import React from 'react';
import {View, Text} from 'react-native';
import MathView from 'react-native-math-view';

const App = () => {
    return (
        <View>
            <Text>Hello</Text>
            <MathView math="\sqrt[2]{25}" />
        </View>
    );
};
export default App;
`

This is the error I get...

Invariant Violation: requireNativeComponent: "RNMathView" was not found in the UIManager.

This error is located at:
    in RNMathView (at MathBaseView.tsx:31)
    in Unknown (at MathView.tsx:17)
    in Unknown (at App.js:9)
    in RCTView (at View.js:32)
    in View (at App.js:7)
    in App (at renderApplication.js:50)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:92)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:43)
    in mathapp(RootComponent) (at renderApplication.js:60)
 ERROR  Invariant Violation: requireNativeComponent: "RNMathView" was not found in the UIManager.

This error is located at:
    in RNMathView (at MathBaseView.tsx:31)
    in Unknown (at MathView.tsx:17)
    in Unknown (at App.js:9)
    in RCTView (at View.js:32)
    in View (at App.js:7)
    in App (at renderApplication.js:50)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:92)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:43)
    in mathapp(RootComponent) (at renderApplication.js:60)

[UPDATE ]

Now I've created a new project, hoping to just migrate files, and I'm getting that it's missing mathjax...!

**Comment by ShaMan123** [comment]
Yeah well react native is quite horrible.
I don't have to enough time to spend on this project.
Keep trying.
If you update react native it's probably the reason.
I understand the frustration.

**Comment by ShaMan123** [comment]
If you're working on android kill gradlew

**Comment by xMxster** [comment]
thanks @ShaMan123 I'll try that.

This is a very wonderful project, hopefully if everything works fine in a new future I might help with it!

**Comment by ShaMan123** [comment]
Thanks, sounds great.

**Comment by xMxster** [comment]
Okay, didn't work haha. I guess I'll have to display stuff manually for awhile lol.

**Comment by ShaMan123** [comment]
I faced similar issues in my projects. Kill gradlew, clear yarn cache, clear react native serve cache, reinstall everything
smash your machine :)

**Comment by xMxster** [comment]
Good news, it's not Math View, apparently it's everything...

I guess you can close the issue (?)

**Comment by ShaMan123** [comment]
Yes, sounds like a caching issue of the react server
