### ISSUE TITLE
can't find variable require

### ISSUE THREAD

**Issue by arifsuheyl** [ShaMan123/react-native-math-view#71]
While importing MathText and Mathview, im getting the error in the picture. There is no error in install. How can I fix this?

<img width="887" alt="Ekran Resmi 2022-05-24 00 36 27" src="https://user-images.githubusercontent.com/59726693/169909837-95bca651-89c2-4f2e-8302-ba1a8cd51c98.png">

**Comment by ShaMan123** [comment]
I don't know.
Try using resolutions field in package.json for react-native.

**Comment by arifsuheyl** [comment]
> 

Thanks. It worked!

**Comment by ShaMan123** [comment]
@kabonKoda what does it fix? What is broken?

**Comment by arifsuheyl** [comment]
> @kabonKoda what does it fix? What is broken?

there was a problem In node_modules/mathjax-full/components/version.js file. 

var load = eval('require');
        var dirname = eval('__dirname');
        var path = load('path');
        return load(path.resolve(dirname, '..', '..', 'package.json')).version;
In this code eval('require') gives an error about require and linking package.json manually worked.

**Comment by pkra** [comment]
If this is related to v3.2.1, then https://github.com/mathjax/MathJax-src/issues/818 is probably worth a read.
