### ISSUE TITLE
Warning with new RN version 0.69+

### ISSUE THREAD

**Issue by rrr3da** [ShaMan123/react-native-math-view#86]
**Description**
Package react-native-math-view contains invalid configuration: "dependency.assets" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.

**To Reproduce**
Add a reference inside package.json to a project pointing to latest RN version and run for iOS. The warn message will appear in the output terminal

**Expected behavior**
No warning is shown

**Comment by ShaMan123** [comment]
welcome to PR
I have abandoned RN but the effort of this repo is worthwhile

**Comment by rrr3da** [comment]
@ShaMan123 you can find my PR #87 
Have a nice day
