### ISSUE TITLE
MathView container styling between Android and iOS is inconsistent

### ISSUE THREAD

**Issue by cyberjam** [ShaMan123/react-native-math-view#93]
Hi ShaMan,
Thanks for making this library.
I'm looking at [this issue](https://github.com/mattermost/mattermost-mobile/pull/7695#issuecomment-1835874283).
#### Summary
Unlike iOS, height of MathView Component is set on Android.

#### Steps to reproduce
It was reproduced using MathView on [mattermost mobile](https://github.com/mattermost/mattermost-mobile/blob/c575e5ed5690af301666bcc1d25c58e3be7ce085/app/components/markdown/markdown_latex_inline/index.tsx#L62C17-L62C17). (Due to the version conflict issue, I couldn't reproduce using the `MathExmaple`)

#### Expected behavior
MathView container styling of Android and ios should be consistent.

#### Observed behavior

|Android (14.0)|iOS (17.0)|
|---|---|
|<img width="264" alt="image" src="https://github.com/ShaMan123/react-native-math-view/assets/20448972/6b397591-7eef-42bb-93bd-0ebb01ef9212">|<img width="273" alt="image" src="https://github.com/ShaMan123/react-native-math-view/assets/20448972/32438719-a331-403d-b264-dbbe76185504">|

#### Possible fixes
There might be a problem with the [android code](https://github.com/ShaMan123/react-native-math-view/blob/9a8794b38f086b9fd1715b50c45483e3e024cce6/src/android/MathBaseView.tsx#L33C25-L33C25) and [container style](https://github.com/ShaMan123/react-native-math-view/blob/9a8794b38f086b9fd1715b50c45483e3e024cce6/src/common.tsx#L62)

ref : [iOS code](https://github.com/ShaMan123/react-native-math-view/blob/9a8794b38f086b9fd1715b50c45483e3e024cce6/src/ios/MathView.tsx#L13)

Before : `style={[styles.container, props.resizeMode === 'contain' && styles.contain, props.style]}`
After : `style={[props.resizeMode === 'contain' && styles.contain, props.style]}`

|Android (Before)|Android (After)|
|---|---|
|<img width="264" alt="image" src="https://github.com/ShaMan123/react-native-math-view/assets/20448972/6b397591-7eef-42bb-93bd-0ebb01ef9212">|<img width="256" alt="image" src="https://github.com/ShaMan123/react-native-math-view/assets/20448972/4804878c-8126-4f31-ba57-65549264c533">|

(Tested on react-native-math-view - 3.9.5)

Thank you for reading. Happy New Year :)

**Comment by cyberjam** [comment]
To ensure consistent heights between Android and iOS, I'm considering using [MathViewFallback](https://github.com/ShaMan123/react-native-math-view/blob/master/src/fallback/SvgXml.tsx) instead of MathView. 

What is the difference between MathView and MathViewFallback? As far as I know, MathViewFallback uses SVG. Is there a difference in performance?

**Comment by ShaMan123** [comment]
I don't actively use or maintain this repo, I abadoned RN.
Welcome to PR and/or join as a contributor.
SVG is significantly slower if I recall correctly

**Comment by cyberjam** [comment]
Thank you for advice ;) Due to performance, I won't use MathViewFallback Component(SVG). I make PR(#94) about this issue to use MathView Component.
